select = ["E", "F", "B", "I", "N", "A", "COM", "C4", "EXE", "ISC", "G", "PIE", "PT", "Q",
		"RSE", "RET", "SIM", "TID", "ARG", "PD", "PL", "NPY", "RUF",
]

line-length = 100
fix = false
show-source = true
target-version = "py38"

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

ignore = [
	"PLR0913",
]
exclude = ["apples_detection/data/components/base.py"]
namespace-packages = ["apples_detection"]

# Ignore 'F401' (unused-import) in all '__init__.py' files.
[per-file-ignores]
"__init__.py" = ["F401"]
"tests/helpers/run_if.py" = ["PLR0912", "PLR0913"]
"apples_detection/data/minneapple.py" = ["ARG002"]
"apples_detection/data/mnist.py" = ["ARG002"]
"apples_detection/models/mnist_module.py" = ["ARG002"]

[pydocstyle]
convention = "google"

[pylint]
max-args = 7
