_target_: apples_detection.models.minneapple_detection.MinneAppleDetectionLitModule

net:
  _target_: apples_detection.models.components.mask_rcnn.MaskRCNN
  num_classes: 2

optimize_computations: false

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0001
