# @package _global_

defaults:
  - _self_
  - data: minneapple # choose datamodule with `test_dataloader()` for evaluation
  - model: minneapple
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: eval

model_name: best_faster_rcnn_09.04.23
save_to: ${paths.metrics_dir}${.model_name}.csv

tags: [dev]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.models_dir}${.model_name}.ckpt
