# @package _global_

defaults:
  - _self_
  - data: minneapple # choose datamodule with `predict_dataloader()` for getting predictions
  - model: minneapple
  - callbacks: predict_writer
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: predict

tags: [dev]

# passing checkpoint path is necessary for getting predictions
ckpt_path: ${path.models_dir}best_model_27.03.23.ckpt
